apiVersion: v1
kind: Template
objects:
 - apiVersion: v1
   kind: BuildConfig
   metadata:
     name: '${IMAGE_NAME}.${IMAGE_VERSION}'
   spec:
     source:
       type: Git
       git:
         uri: 'https://github.com/shaded-enmity/ci-systems'
         ref: 'master'
       contextDir: '${CONTEXT}'
     strategy:
       type: Docker
       dockerStrategy:
     output:
       to:
         kind: ImageStreamTag
         name: '${IMAGE_NAME}:${IMAGE_VERSION}'
   name: '${IMAGE_NAME}.${IMAGE_VERSION}'
parameters:
 - name: IMAGE_NAME
   description: 'Name of the image'
   required: true
 - name: IMAGE_VERSION
   description: 'Version of the image'
   required: true
 - name: CONTEXT
   description: 'Build context directory'
   required: true
